name: ExoPlayer FFmpeg Extension / Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

env:
  NDK_VERSION: r21e  # 使用 r21e 版本标识符
  NDK_SHA1: c3ebc83c96a4d7f539bd72c241b2be9dcd29bda9  # 对应 Linux 版本的 SHA1 校验值

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Cache NDK
        uses: actions/cache@v3
        with:
          path: ~/android-ndk-${{ env.NDK_VERSION }}
          key: ${{ runner.os }}-${{ env.NDK_VERSION }}

      - name: Download and extract NDK r21e
        run: |
          # 下载 NDK
          curl -Lo ndk.zip https://dl.google.com/android/repository/android-ndk-${{  env.NDK_VERSION }}-linux-x86_64.zip

          # 验证 SHA1 校验值（可选但推荐）
          echo "${{ env.NDK_SHA1 }}  ndk.zip" | sha1sum -c || (echo "SHA1 校验失败！"; exit 1)

          # 解压 NDK
          unzip -q ndk.zip -d ~/
          rm ndk.zip

          # 设置环境变量
          echo "ANDROID_NDK_HOME=~/android-ndk-${{ env.NDK_VERSION }}" >> $GITHUB_ENV

      - name: Build ffmpeg
        run: ./build.sh

      - name: Build extension and publish library locally
        run: ./gradlew :exoplayer-ffmpeg-extension:publishToMavenLocal
