name: ExoPlayer FFmpeg Extension / Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

env:
  NDK_VER: 21.4.7075529

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Cache NDK
        uses: actions/cache@v3
        with:
          path: /usr/local/lib/android/sdk/ndk/${{ env.NDK_VER }}
          key: ${{ runner.os }}-${{ env.NDK_VER }}

      - name: Download and extract NDK r21e
        run: |
          # 创建目标目录（如果不存在）
          sudo mkdir -p /usr/local/lib/android/sdk/ndk/${{ env.NDK_VER }}
          sudo chmod -R 777 /usr/local/lib/android/sdk/ndk

          # 下载 NDK
          curl -Lo ndk.zip https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip 

          # 解压 NDK 到指定路径
          sudo unzip -q ndk.zip -d /usr/local/lib/android/sdk/ndk/
          sudo rm ndk.zip

          # 设置环境变量
          echo "ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/${{ env.NDK_VER }}" >> $GITHUB_ENV

      - name: Build ffmpeg
        run: ./build.sh

      - name: Build extension and publish library locally
        run: ./gradlew :exoplayer-ffmpeg-extension:publishToMavenLocal
